export const GET_TABLE_DATA = "GET_TABLE_DATA";
export const GET_TABLE_DATA_SUCCESS = "GET_TABLE_DATA_SUCCESS";
export const GET_TABLE_DATA_FAIL = "GET_TABLE_DATA_FAIL";

export const DELETE_THIS_USER = "DELETE_THIS_USER";
export const DELETE_THIS_USER_SUCCESS = "DELETE_THIS_USER_SUCCESS";
export const DELETE_THIS_USER_FAIL = "DELETE_THIS_USER_FAIL";

export const GET_POST_DATA = "GET_POST_DATA";
export const GET_POST_DATA_SUCCESS = "GET_POST_DATA_SUCCESS";
export const GET_POST_DATA_FAIL = "GET_POST_DATA_FAIL";

export const ADD_NEW_POST = "ADD_NEW_POST";
export const ADD_NEW_POST_SUCCESS = "ADD_NEW_POST_SUCCESS";
export const ADD_NEW_POST_FAIL = "ADD_NEW_POST_FAIL";

export const EDIT_THIS_POST = "EDIT_THIS_POST";
export const EDIT_THIS_POST_SUCCESS = "EDIT_THIS_POST_SUCCESS";
export const EDIT_THIS_POST_FAIL = "EDIT_THIS_POST_FAIL";
